[package]
name = "sysapi"
version = "0.2.1"
authors = ["Daniel (dmilith) Dettlaff <dmilith@me.com>"]

[dependencies]
gotham = "0.2"
gotham_derive = "0.2"
log = "0.4"
simple_logger = "1.0"
hyper = { version = "0.11", features = [] }
serde = "1"
serde_derive = "1"
bincode = "1"
mime = "0.3"
futures = "0.1"
tokio-core = "0.1"
mio = "0.6"
borrow-bag = "1"
url = "1"
uuid = { version = "0.6", features = ["v4"] }
chrono = "0.4"
base64 = "0.9"
rand = "0.4"
linked-hash-map = "0.5"
num_cpus = "1.2"
crossbeam = "0.3"
regex = "0.2"
lazy_static = "1.1"
